//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing.LabelPrinting {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomException", Namespace="http://schemas.datacontract.org/2004/07/LabelPrinting")]
    [System.SerializableAttribute()]
    public partial class CustomException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MesssageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Messsage {
            get {
                return this.MesssageField;
            }
            set {
                if ((object.ReferenceEquals(this.MesssageField, value) != true)) {
                    this.MesssageField = value;
                    this.RaisePropertyChanged("Messsage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LabelPrinting.ILabelPrintingService")]
    public interface ILabelPrintingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILabelPrintingService/GenerateLabelPreview", ReplyAction="http://tempuri.org/ILabelPrintingService/GenerateLabelPreviewResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Testing.LabelPrinting.CustomException), Action="http://tempuri.org/ILabelPrintingService/GenerateLabelPreviewCustomExceptionFault" +
            "", Name="CustomException", Namespace="http://schemas.datacontract.org/2004/07/LabelPrinting")]
        byte[] GenerateLabelPreview(byte[] inputBytes, string printerName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILabelPrintingServiceChannel : Testing.LabelPrinting.ILabelPrintingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LabelPrintingServiceClient : System.ServiceModel.ClientBase<Testing.LabelPrinting.ILabelPrintingService>, Testing.LabelPrinting.ILabelPrintingService {
        
        public LabelPrintingServiceClient() {
        }
        
        public LabelPrintingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LabelPrintingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LabelPrintingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LabelPrintingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] GenerateLabelPreview(byte[] inputBytes, string printerName) {
            return base.Channel.GenerateLabelPreview(inputBytes, printerName);
        }
    }
}
